### ISSUE TITLE
Grow and adapt mixins don't behave as columns when grow content wraps

### ISSUE THREAD

**Issue by danevans** [Coffeekraken/gridle#122]
With long text that wraps in the grow class notice that the two columns stack instead of appearing side by side horizontally. Notice that this is not true when the text doesn't wrap or when using the non-flex version.

![screen shot 2017-02-23 at 6 09 28 pm](https://cloud.githubusercontent.com/assets/214379/23287596/42727ef6-f9f3-11e6-9dcd-3147a5d85462.png)

SCSS:
```scss
@import "gridle/gridle-flex";

@include gridle_setup( (
  context: 12,
  gutter-width: 16px,
  direction: ltr
) );

@include gridle_init();

.app {
  width: 400px;
}

.my-container {
  @include gridle_container();
}

.my-row {
  @include gridle_row();
}

.my-checkbox {
  @include gridle( adapt );
}

.my-label {
  @include gridle( grow );
}
```

HTML
```html
<div class="app">
  <div class="my-container">
    <div class="my-row">
      <div class="my-checkbox">
        <input type="checkbox" />
      </div>
      <label class="my-label">
        Some really long text to wrap around and around and around and around and around and around
      </label>
    </div>

    <div class="my-row">
      <div class="my-checkbox">
        <input type="checkbox" />
      </div>
      <label class="my-label">
        Some short text
      </label>
    </div>
  </div>
</div>
```
